config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tables, only: %i[show index create] do
    patch :join, on: :member
    resources :rounds, only: %i[show create] do
      member do
        patch :swap_cards
        patch :ready
        patch :throw_cards
        patch :take_cards
        patch :take_blind_card
      end
    end
  end

  root to: 'tables#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/tables_controller.rb
# frozen_string_literal: true

class TablesController < ApplicationController
  before_action :set_table, only: [:show, :join]

  def index; end

  def show
    return unless @table.rounds.last
    return if @table.rounds.last.game.game_over

    redirect_to :root, notice: "Sorry. You're too late. Game has already been started. Try another one."
  end

  def join
    # TODO query in SQL if table has pending games instead
    if @table.players.count > 3 || @table.rounds.any? { |r| !r.game.game_over }
      redirect_to :root, notice: 'Sorry. Table is full or a game has already been started. Try another one.'

      return
    end

    join_player

    redirect_to table_path(@table)
  end

  def create
    @table = Table.create
    join_player

    redirect_to table_path(@table)
  end

  private

  def set_table
    @table = Table.find_by_id(params[:id])
  end

  def join_player
    return if @table.players&.pluck('id')&.include?(Current.player.id)

    @table.players << Current.player.to_h
    @table.save

    TableChannel.broadcast_to(@table, { gamemaster: @table.players.first, players: @table.players })
  end
end

app/views/tables/index.haml
%h1 Join or make a new table

%h4
  = "player: #{ Current.player.name }"

= button_to 'Create Table', tables_path

app/views/tables/show.haml
%h1 Table

%ul#players
  - @table.players.each_with_index do |player, index|
    %li= "#{player['name']} #{'(Gamemaster)' if index.zero?}"

= button_to 'Start Game', table_rounds_path(@table),
  id: :start_game_button,
  remote: true,
  form: { 'data-type': :json },
  data: { player: Current.player.id, disable_with: 'starting...' },
  hidden: @table.players.first['id'] != Current.player.id

= button_to 'Join Table', join_table_path(@table),
  hidden: (@table.players.count > 3 || @table.players.pluck('id').include?(Current.player.id)),
  id: :join_table_button,
  method: :patch,
  form: { 'data-type': :json },
  data: { player: Current.player.id, disable_with: 'joining...' }